### ISSUE TITLE
Seems failed in boost 1.82

### ISSUE THREAD

**Issue by ILikeIneine** [nicktrandafil/PriorityStrand#1]
The PriorityStrand stucked and ran into a deadlock while benchmarking.

Here is the godbolt link: [LINK](https://godbolt.org/z/hWhxGzx15)

Could you please have a look and find out where the problems are?

Actually I'm learning boost asio, and your implementation does help me a lot! Thanks!

**Comment by ILikeIneine** [comment]
I used std::mutex other than Spinlock in Impl of PriorityStrandService, Is it necessary?

**Comment by nicktrandafil** [comment]
I moved

```
timer.cancel();
t1.join();
t2.join();
```

out of the loop, because on the second iteration of the loop the `io_context` is stopped, that is how you get dead lock. This [godbolt](https://godbolt.org/z/eTfxn1xvr) works.

**Comment by nicktrandafil** [comment]
> I used std::mutex other than Spinlock in Impl of PriorityStrandService, Is it necessary?

No, it is not necessary. I imagined it would be faster (at the expense of wasting CPU cycles) than `std::mutex` but I never measured it.

**Comment by ILikeIneine** [comment]
> that is how you get dead lock.

Ooops! Sorry for that stupid typo I've made...  Actually I'm not quite familiar with benchmark and some bad ruined my brain while copying the previous benchmark code block :(

Again thanks for your help! 🫶

**Comment by nicktrandafil** [comment]
You are welcome
